# Generated by Django 3.1.6 on 2021-03-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210312_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='testproduct'),
            preserve_default=False,
        ),
    ]
